import React, { useEffect, useState } from 'react';
import { ScrollView, Share, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';

import CosmicBackground from '../components/cosmic/CosmicBackground';
import ScreenHeader from '../components/ui/ScreenHeader';
import GlassCard from '../components/ui/GlassCard';
import CosmicButton from '../components/ui/CosmicButton';
import Skeleton from '../components/ui/Skeleton';
import BirthChartPreview from '../components/astrology/BirthChartPreview';
import CosmicIcon, { IconName } from '../components/ui/CosmicIcon';
import { astrologyService, ChartCardData } from '../services/astrologyService';
import { analytics, Events } from '../services/analyticsService';
import type { NatalChart } from '../services/astroEngine';
import { colors } from '../theme/colors';
import { spacing } from '../theme/spacing';
import { typography, fonts } from '../theme/typography';
import { MainStackParamList } from '../navigation/routes';

const items: {
  key: keyof ChartCardData;
  icon: IconName;
  title: string;
}[] = [
  { key: 'sun', icon: 'sun', title: 'Sun Sign' },
  { key: 'moon', icon: 'moon', title: 'Moon Sign' },
  { key: 'ascendant', icon: 'arrow-up', title: 'Ascendant' },
  { key: 'dominant', icon: 'star', title: 'Dominant Planet' },
];

export default function BirthChartScreen() {
  const navigation = useNavigation<NativeStackNavigationProp<MainStackParamList>>();
  const [chart, setChart] = useState<ChartCardData | null>(null);
  const [natal, setNatal] = useState<NatalChart | null>(null);

  useEffect(() => {
    let active = true;
    Promise.all([
      astrologyService.getBirthChart(),
      astrologyService.getNatalChart(),
    ]).then(([c, n]) => {
      if (!active) return;
      setChart(c);
      setNatal(n);
    });
    return () => {
      active = false;
    };
  }, []);

  return (
    <CosmicBackground intensity="low" showZodiacWheel>
      <SafeAreaView style={{ flex: 1 }} edges={['top']}>
        <ScreenHeader title="My Cosmic Chart" subtitle="Your planetary blueprint" />
        <ScrollView
          contentContainerStyle={styles.scroll}
          showsVerticalScrollIndicator={false}
        >
          <View style={styles.chartWrap}>
            <BirthChartPreview size={300} chart={natal} />
          </View>

          <View style={styles.grid}>
            {items.map((it) => {
              const data = chart?.[it.key];
              return (
                <View key={it.key} style={styles.cell}>
                  <GlassCard padding={spacing.md} style={{ flex: 1 }}>
                    <View style={styles.cardHead}>
                      <View style={styles.iconWrap}>
                        <CosmicIcon name={it.icon} color={colors.goldPrimary} size={16} />
                      </View>
                      <Text style={styles.cardTitle}>{it.title}</Text>
                    </View>
                    {data ? (
                      <>
                        <Text style={styles.cardValue}>{data.name}</Text>
                        <Text style={styles.cardDetail}>{data.detail}</Text>
                      </>
                    ) : (
                      <View style={{ marginTop: spacing.sm, gap: 6 }}>
                        <Skeleton variant="line" width="70%" height={14} />
                        <Skeleton variant="line" width="100%" height={10} />
                        <Skeleton variant="line" width="80%" height={10} />
                      </View>
                    )}
                  </GlassCard>
                </View>
              );
            })}
          </View>

          <CosmicButton
            title="Ask AI to Explain My Chart"
            icon="sparkle"
            onPress={() => navigation.navigate('Chat' as any)}
            disabled={!chart}
            style={{ marginTop: spacing.lg }}
          />
          <CosmicButton
            title="Share my chart"
            icon="arrow-up"
            variant="glass"
            disabled={!chart}
            onPress={async () => {
              if (!chart) return;
              const message =
                `✦ My Cosmic Chart\n` +
                `${chart.sun.name}\n${chart.moon.name}\n` +
                `${chart.ascendant.name}\n${chart.dominant.name}\n\n` +
                `Generated by CosmicSelf`;
              try {
                await Share.share({ title: 'My cosmic chart', message });
                analytics.track(Events.ShareCompleted, { surface: 'birth_chart' });
              } catch {
                /* user dismissed */
              }
            }}
            style={{ marginTop: spacing.sm }}
          />
        </ScrollView>
      </SafeAreaView>
    </CosmicBackground>
  );
}

const styles = StyleSheet.create({
  scroll: {
    paddingHorizontal: spacing.screenH,
    paddingBottom: 120,
  },
  chartWrap: {
    alignItems: 'center',
    marginVertical: spacing.md,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: spacing.md,
    marginTop: spacing.md,
    justifyContent: 'space-between',
  },
  cell: {
    width: '48.5%',
  },
  cardHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  iconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(246,200,95,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(246,200,95,0.4)',
  },
  cardTitle: {
    ...typography.caption,
    color: colors.textSecondary,
    fontFamily: fonts.bodySemibold,
    letterSpacing: 0.4,
  },
  cardValue: {
    ...typography.section,
    fontSize: 16,
    color: colors.goldBright,
    marginTop: spacing.sm,
  },
  cardDetail: {
    ...typography.caption,
    color: colors.textMuted,
    marginTop: 2,
    lineHeight: 16,
  },
});
